# Site settings
title: Sound Shikari Productions
email: prodbysoundshikari@gmail.com
description: "This is the official website of Sound Shikari Productions."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://soundshikari.github.io" # the base hostname & protocol for your site
twitter_username: isoundshikari
github_username:  

# Build settings
markdown: kramdown
